apiVersion: v1
kind: Pod
metadata:
  name: openfaas-managed-filestore-pvc-inspector
  namespace: openfaas-tiering
spec:
  containers:
  - name: openfaas-managed-filestore-pvc-inspector-container
    image: busybox:stable
    #image: alpine:3
    command: ["tail"]
    args: ["-f", "/dev/null"] # This keeps the pod running
    volumeMounts:
    - name: app-storage-volume
      mountPath: /data
  volumes:
  - name: app-storage-volume
    persistentVolumeClaim:
      claimName: managed-filestore-pvc 