# openfaas-preprocessor-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openfaas-preprocessor-pvc
  namespace: openfaas-tiering
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte of storage
  storageClassName: standard # Or your custom StorageClass name
  
# Apply with 'kubectl apply -f openfaas-tiering-pvc.yaml'

# References
# https://www.google.com/search?q=deploying+a+flask+app+as+a+container+to+an+existing+kubernetes+cluster+with+an+external+address+exposed+and+that+can+write+to+persistent+storage&sca_esv=89c0b9e6faeb52cb&rlz=1C1CHBF_enUS1071US1071&ei=B34Dab6xAZStmtkPzs6PsAI&ved=0ahUKEwj-0JrOmMyQAxWUliYFHU7nAyYQ4dUDCBM&uact=5&oq=deploying+a+flask+app+as+a+container+to+an+existing+kubernetes+cluster+with+an+external+address+exposed+and+that+can+write+to+persistent+storage&gs_lp=Egxnd3Mtd2l6LXNlcnAikAFkZXBsb3lpbmcgYSBmbGFzayBhcHAgYXMgYSBjb250YWluZXIgdG8gYW4gZXhpc3Rpbmcga3ViZXJuZXRlcyBjbHVzdGVyIHdpdGggYW4gZXh0ZXJuYWwgYWRkcmVzcyBleHBvc2VkIGFuZCB0aGF0IGNhbiB3cml0ZSB0byBwZXJzaXN0ZW50IHN0b3JhZ2VIAFAAWABwAHgBkAEAmAEAoAEAqgEAuAEDyAEA-AEBmAIAoAIAmAMAkgcAoAcAsgcAuAcAwgcAyAcA&sclient=gws-wiz-serp